"""
pdf_report.py
--------------
Builds the downloadable clinical PDF for a single prediction, and a summary PDF
for a batch of predictions.

Uses ReportLab's platypus layer (flowables) rather than raw canvas drawing so
long content — a big explanation table, multi-line doctor notes — reflows onto
extra pages instead of running off the bottom of page one.
"""

from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)

from clinical_scores import compute_all
from preprocessing import FIELD_META, REFERENCE_RANGES, flag_abnormal

PRIMARY = colors.HexColor("#1a73e8")
DANGER = colors.HexColor("#e8534f")
SUCCESS = colors.HexColor("#34a853")
MUTED = colors.HexColor("#5f6b7a")
LIGHT_ROW = colors.HexColor("#f4f8fd")

DISCLAIMER = (
    "<b>Disclaimer:</b> This report is generated by an automated machine-learning "
    "decision-support tool for academic use. It is <b>not</b> a medical diagnosis and "
    "must not replace evaluation by a licensed hepatologist or gastroenterologist. "
    "Model output should be interpreted alongside full clinical history, imaging, and "
    "confirmatory testing."
)


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("T", parent=base["Heading1"], fontSize=17, textColor=colors.white,
                                spaceAfter=0, leading=21),
        "subtitle": ParagraphStyle("ST", parent=base["Normal"], fontSize=9,
                                   textColor=colors.white, leading=12),
        "h2": ParagraphStyle("H2", parent=base["Heading2"], fontSize=12, textColor=PRIMARY,
                             spaceBefore=12, spaceAfter=6),
        "body": ParagraphStyle("B", parent=base["Normal"], fontSize=9, leading=13),
        "small": ParagraphStyle("S", parent=base["Normal"], fontSize=7.5, textColor=MUTED,
                                leading=10),
        "cell": ParagraphStyle("C", parent=base["Normal"], fontSize=8, leading=11),
        "center": ParagraphStyle("CT", parent=base["Normal"], fontSize=9, alignment=TA_CENTER),
    }


def _header_footer(canvas, doc):
    """Blue banner on every page plus a page number in the footer."""
    canvas.saveState()
    width, height = A4

    canvas.setFillColor(PRIMARY)
    canvas.rect(0, height - 2.4 * cm, width, 2.4 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 15)
    canvas.drawString(1.6 * cm, height - 1.35 * cm, "LiverAI  |  Cirrhosis Risk Assessment Report")
    canvas.setFont("Helvetica", 8)
    canvas.drawString(1.6 * cm, height - 1.9 * cm,
                      "AI-assisted clinical decision support - not a diagnosis")

    canvas.setFillColor(MUTED)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawString(1.6 * cm, 1.1 * cm,
                      f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    canvas.drawRightString(width - 1.6 * cm, 1.1 * cm, f"Page {doc.page}")
    canvas.setStrokeColor(colors.HexColor("#dde5ee"))
    canvas.line(1.6 * cm, 1.5 * cm, width - 1.6 * cm, 1.5 * cm)
    canvas.restoreState()


def _kv_table(rows, col_widths):
    table = Table(rows, colWidths=col_widths, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8f0fe")),
        ("TEXTCOLOR", (0, 0), (-1, 0), PRIMARY),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_ROW]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#dde5ee")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
    ]))
    return table


def build_prediction_pdf(buffer, record, explanation=None, clinician_name=""):
    """Render one prediction into `buffer` as a multi-section PDF."""
    styles = _styles()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=1.6 * cm, rightMargin=1.6 * cm,
        topMargin=3.0 * cm, bottomMargin=2.0 * cm,
        title=f"LiverAI Report - {record.patient_name}",
        author="LiverAI",
    )

    story = []
    inputs = record.clinical_inputs()
    is_high_risk = record.result == "High Risk"
    risk_colour = DANGER if is_high_risk else SUCCESS

    # --- Patient / report metadata ---------------------------------------
    story.append(Paragraph("Patient & Report Details", styles["h2"]))
    meta_rows = [
        ["Field", "Value", "Field", "Value"],
        ["Patient Name", record.patient_name or "-",
         "Patient ID", record.patient_id or "-"],
        ["Age", f"{record.age:g} years" if record.age else "-",
         "Gender", {"M": "Male", "F": "Female"}.get(record.gender, record.gender or "-")],
        ["Assessment Date", record.created_at.strftime("%d %b %Y, %H:%M") if record.created_at else "-",
         "Report ID", f"LAI-{record.id:06d}"],
        ["Model", record.model_name or "RandomForest",
         "Reviewing Clinician", clinician_name or "-"],
    ]
    story.append(_kv_table(meta_rows, [3.2 * cm, 4.6 * cm, 3.4 * cm, 4.6 * cm]))

    # --- Result banner ----------------------------------------------------
    story.append(Spacer(1, 0.5 * cm))
    result_table = Table([[
        Paragraph(f"<b><font size=15 color='white'>{record.result}</font></b><br/>"
                  f"<font size=8 color='white'>Model classification</font>", styles["body"]),
        Paragraph(f"<b><font size=15 color='white'>{record.probability_pct}%</font></b><br/>"
                  f"<font size=8 color='white'>Confidence score</font>", styles["body"]),
        Paragraph(f"<b><font size=15 color='white'>{record.risk_level}</font></b><br/>"
                  f"<font size=8 color='white'>Risk band</font>", styles["body"]),
    ]], colWidths=[5.3 * cm, 5.3 * cm, 5.3 * cm])
    result_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), risk_colour),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("BOX", (0, 0), (-1, -1), 0.5, risk_colour),
        ("INNERGRID", (0, 0), (-1, -1), 0.6, colors.white),
    ]))
    story.append(result_table)

    # --- Clinical panel with reference ranges -----------------------------
    story.append(Paragraph("Clinical Laboratory Panel", styles["h2"]))
    flags = flag_abnormal({k: v for k, v in inputs.items() if v is not None})
    panel_rows = [["Parameter", "Value", "Unit", "Reference Range", "Status"]]
    for field in ["bilirubin", "cholesterol", "albumin", "copper", "alk_phos",
                  "sgot", "triglycerides", "platelets", "prothrombin"]:
        value = inputs.get(field)
        meta = FIELD_META[field]
        reference = REFERENCE_RANGES.get(field)
        flag = flags.get(field, {})
        status = flag.get("status", "-")
        panel_rows.append([
            meta["label"],
            f"{value:g}" if value is not None else "-",
            meta["unit"],
            f"{reference[0]} - {reference[1]}" if reference else "-",
            status.upper() if status != "-" else "-",
        ])

    panel = _kv_table(panel_rows, [4.6 * cm, 2.4 * cm, 2.4 * cm, 3.6 * cm, 2.9 * cm])
    # Colour the status column so abnormal values are findable at a glance.
    extra_styles = []
    for row_index, field in enumerate(
        ["bilirubin", "cholesterol", "albumin", "copper", "alk_phos",
         "sgot", "triglycerides", "platelets", "prothrombin"], start=1
    ):
        status = flags.get(field, {}).get("status")
        if status in ("high", "low"):
            extra_styles.append(("TEXTCOLOR", (4, row_index), (4, row_index), DANGER))
            extra_styles.append(("FONTNAME", (4, row_index), (4, row_index), "Helvetica-Bold"))
        elif status == "normal":
            extra_styles.append(("TEXTCOLOR", (4, row_index), (4, row_index), SUCCESS))
    panel.setStyle(TableStyle(extra_styles))
    story.append(panel)

    # --- Physical examination findings ------------------------------------
    story.append(Paragraph("Physical Examination & Staging", styles["h2"]))
    yes_no = {"Y": "Present", "N": "Absent"}
    exam_rows = [
        ["Finding", "Result", "Finding", "Result"],
        ["Ascites", yes_no.get(record.ascites, record.ascites or "-"),
         "Hepatomegaly", yes_no.get(record.hepatomegaly, record.hepatomegaly or "-")],
        ["Spider Angiomas", yes_no.get(record.spiders, record.spiders or "-"),
         "Edema", {"N": "None", "S": "Slight", "Y": "Present"}.get(record.edema, record.edema or "-")],
        ["Histologic Stage", f"Stage {record.stage}" if record.stage else "-", "", ""],
    ]
    story.append(_kv_table(exam_rows, [4.0 * cm, 3.9 * cm, 4.0 * cm, 3.9 * cm]))

    # --- Established clinical scores --------------------------------------
    scores = compute_all({k: v for k, v in inputs.items() if v is not None})
    story.append(Paragraph("Established Clinical Scores (for cross-reference)", styles["h2"]))
    score_rows = [["Score", "Value", "Band", "Interpretation"]]
    for key in ("meld", "fib4", "apri", "child_pugh"):
        entry = scores[key]
        value = entry["value"]
        score_rows.append([
            entry["label"],
            str(value) if value is not None else "N/A",
            entry["band"],
            Paragraph(f"<font size=7.5>{entry['meaning']}</font>", styles["cell"]),
        ])
    story.append(_kv_table(score_rows, [4.0 * cm, 2.0 * cm, 2.4 * cm, 7.5 * cm]))
    story.append(Spacer(1, 0.15 * cm))
    story.append(Paragraph(
        "These are deterministic literature formulas, not model output. "
        + " ".join(scores[k]["note"] for k in ("meld", "fib4", "apri")),
        styles["small"],
    ))

    # --- Per-prediction explanation ---------------------------------------
    explanation = explanation if explanation is not None else record.explanation
    if explanation:
        story.append(Paragraph("What Drove This Prediction", styles["h2"]))
        story.append(Paragraph(
            "Each factor was re-scored against a typical patient's value to measure how much "
            "it moved this patient's risk. Positive values pushed the risk up.",
            styles["small"],
        ))
        story.append(Spacer(1, 0.2 * cm))
        driver_rows = [["Factor", "This Patient", "Typical", "Effect on Risk"]]
        for item in explanation:
            patient_value = item.get("patient_value")
            driver_rows.append([
                item.get("label", item.get("feature", "-")),
                f"{patient_value:g}" if isinstance(patient_value, (int, float)) else str(patient_value or "-"),
                str(item.get("typical_value", "-")),
                f"{item.get('impact_pct', 0):+.1f}%  ({item.get('direction', '')})",
            ])
        drivers = _kv_table(driver_rows, [4.6 * cm, 3.0 * cm, 2.6 * cm, 5.7 * cm])
        for row_index, item in enumerate(explanation, start=1):
            colour = DANGER if item.get("impact", 0) > 0 else SUCCESS
            drivers.setStyle(TableStyle([("TEXTCOLOR", (3, row_index), (3, row_index), colour)]))
        story.append(drivers)

    # --- Recommendations ---------------------------------------------------
    story.append(Paragraph("Suggested Next Steps", styles["h2"]))
    if is_high_risk:
        recommendations = [
            "Refer to hepatology/gastroenterology for confirmatory assessment.",
            "Consider abdominal ultrasound with Doppler, and transient elastography (FibroScan).",
            "Review the medication list for hepatotoxic agents and adjust as indicated.",
            "Monitor bilirubin, albumin, platelet count and prothrombin time trends.",
            "Screen for varices and hepatocellular carcinoma per local guidelines.",
            "Counsel on alcohol avoidance, hepatitis vaccination, and nutritional support.",
        ]
    else:
        recommendations = [
            "Continue routine liver panel monitoring at the usual interval.",
            "Reassess promptly if jaundice, ascites, oedema or encephalopathy develop.",
            "Address modifiable risk factors: alcohol intake, metabolic syndrome, weight.",
            "Ensure hepatitis A/B vaccination status is current.",
        ]
    for item in recommendations:
        story.append(Paragraph(f"&bull;&nbsp; {item}", styles["body"]))
        story.append(Spacer(1, 0.08 * cm))

    # --- Doctor notes -----------------------------------------------------
    if record.doctor_notes:
        story.append(Paragraph("Clinician Notes", styles["h2"]))
        # Escape so a note containing '<' can't break the PDF markup.
        safe_notes = (record.doctor_notes
                      .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                      .replace("\n", "<br/>"))
        story.append(Paragraph(safe_notes, styles["body"]))

    story.append(Spacer(1, 0.6 * cm))
    story.append(Paragraph(DISCLAIMER, styles["small"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer


def build_batch_pdf(buffer, rows, clinician_name=""):
    """Summary PDF for a batch run: one table row per patient."""
    styles = _styles()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=1.6 * cm, rightMargin=1.6 * cm,
        topMargin=3.0 * cm, bottomMargin=2.0 * cm,
        title="LiverAI Batch Assessment Summary", author="LiverAI",
    )

    story = [Paragraph("Batch Assessment Summary", styles["h2"])]
    high_risk_count = sum(1 for r in rows if r.result == "High Risk")
    story.append(Paragraph(
        f"{len(rows)} patient record(s) assessed &mdash; "
        f"<font color='#e8534f'><b>{high_risk_count} high risk</b></font>, "
        f"<font color='#34a853'><b>{len(rows) - high_risk_count} low risk</b></font>. "
        f"Prepared by {clinician_name or 'LiverAI'}.",
        styles["body"],
    ))
    story.append(Spacer(1, 0.4 * cm))

    table_rows = [["#", "Patient", "Age", "Stage", "Result", "Confidence", "Risk Band", "MELD"]]
    for index, record in enumerate(rows, start=1):
        scores = compute_all({k: v for k, v in record.clinical_inputs().items() if v is not None})
        meld = scores["meld"]["value"]
        table_rows.append([
            str(index),
            Paragraph(f"<font size=7.5>{record.patient_name}</font>", styles["cell"]),
            f"{record.age:g}" if record.age else "-",
            str(record.stage or "-"),
            record.result,
            f"{record.probability_pct}%",
            record.risk_level,
            str(meld) if meld is not None else "-",
        ])

    table = _kv_table(table_rows,
                      [0.9 * cm, 4.3 * cm, 1.3 * cm, 1.3 * cm, 2.4 * cm, 2.2 * cm, 2.2 * cm, 1.4 * cm])
    for row_index, record in enumerate(rows, start=1):
        colour = DANGER if record.result == "High Risk" else SUCCESS
        table.setStyle(TableStyle([("TEXTCOLOR", (4, row_index), (4, row_index), colour)]))
    story.append(table)

    story.append(Spacer(1, 0.6 * cm))
    story.append(Paragraph(DISCLAIMER, styles["small"]))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer
